# US - Baby Names

### Introduction:

We are going to use a subset of [US Baby Names](https://www.kaggle.com/kaggle/us-baby-names) from Kaggle.  
In the file it will be names from 2004 until 2014


### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv).

### Step 3. Assign it to a variable called baby_names.

In [66]:
df = pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv')

### Step 4. See the first 10 entries

In [67]:
df.head(10)

   Unnamed: 0     Id      Name  Year Gender State  Count
0       11349  11350      Emma  2004      F    AK     62
1       11350  11351   Madison  2004      F    AK     48
2       11351  11352    Hannah  2004      F    AK     46
3       11352  11353     Grace  2004      F    AK     44
4       11353  11354     Emily  2004      F    AK     41
5       11354  11355   Abigail  2004      F    AK     37
6       11355  11356    Olivia  2004      F    AK     33
7       11356  11357  Isabella  2004      F    AK     30
8       11357  11358    Alyssa  2004      F    AK     29
9       11358  11359    Sophia  2004      F    AK     28

### Step 5. Delete the column 'Unnamed: 0' and 'Id'

In [68]:
df = df.drop(labels=['Unnamed: 0', 'Id'], axis=1)
df.head()

      Name  Year Gender State  Count
0     Emma  2004      F    AK     62
1  Madison  2004      F    AK     48
2   Hannah  2004      F    AK     46
3    Grace  2004      F    AK     44
4    Emily  2004      F    AK     41

### Step 6. What year has the highest number of baby names in the dataset?

In [72]:
df[['Count','Year']].groupby('Year').sum().idxmax()

Count    2007
dtype: int64

### Step 7. Is there more male or female names in the dataset?

In [38]:
df[['Gender','Name']].drop_duplicates().groupby(['Gender']).count()

         Name
Gender
F       10929
M        8012

### Step 8. Group the dataset by name and assign to names

In [76]:
names_df = df.groupby(['Name']).sum()

### Step 9. How many different names exist in the dataset?

In [42]:
df['Name'].drop_duplicates().count()

np.int64(17632)

### Step 10. What is the name with most occurrences?

In [74]:
df.groupby(['Name']).sum().sort_values('Count',ascending=False).idxmax()

Year        Riley
Gender     Oliver
State     Coalton
Count       Jacob
dtype: object

### Step 11. How many different names have the least occurrences?

In [80]:
len(names_df[names_df.Count == names_df.Count.min()])

2578

### Step 12. What is the median name occurrence?

In [81]:
names_df.Count.median()

49.0

### Step 13. What is the standard deviation of names?

In [83]:
names_df.Count.std()

count     17632.000000
mean       2008.932169
std       11006.069468
min           5.000000
25%          11.000000
50%          49.000000
75%         337.000000
max      242874.000000
Name: Count, dtype: float64

### Step 14. Get a summary with the mean, min, max, std and quartiles.

In [84]:
names_df.Count.describe()

count     17632.000000
mean       2008.932169
std       11006.069468
min           5.000000
25%          11.000000
50%          49.000000
75%         337.000000
max      242874.000000
Name: Count, dtype: float64